### ISSUE TITLE
Crashes at launch on Tahoe

### ISSUE THREAD

**Issue by girlsperhour** [luckman212/frontapp#2]
Crashes at launch on macOS 26.0.1.

Have a serious focus loss issue on my machine so would love to get this working.

**Comment by luckman212** [comment]
I'm on 26.1 and the app runs for me. I admit I didn't try it on 26.0.1 though.

Can you try opening a Terminal, and running the app from there so we can see if any debug output appears?

```
/Applications/frontapp.app/Contents/MacOS/frontapp
```

**Comment by girlsperhour** [comment]
Sorry it took so long to reply to this. Launching from the Terminal, it still crashes and spits out this:

`zsh: trace trap  /Users/me/Downloads/frontapp.app/Contents/MacOS/frontapp`

**Comment by luckman212** [comment]
Strange. Seems like a possible Gatekeeper issue. It's a longshot, but I've just pushed a fresh build [1.1.3](https://github.com/luckman212/frontapp/releases/tag/1.1.3) that is also notarized and uses the hardened runtime. Could you try that?

**Comment by girlsperhour** [comment]
Still getting the trace trap line, even when launched from within package contents (through the Finder or Terminal).

**Comment by luckman212** [comment]
Would you mind sharing a logarchive from your system so I can look for any hints as to what's causing this?

Reproduce the issue and then run the command below from Terminal:

```
log collect --last 3m --output /tmp/logs_$(date +%s).logarchive
```

If you can upload the resulting logarchive file to [xfer.reliable.network](https://xfer.reliable.network/) I'll have a look (no need to post the URL publicly, I will see it on the backend)

**Comment by girlsperhour** [comment]
~~Alright I think it uploaded.~~ Sorry I didn't realize how big the archive was and now I'm uploading an archive of it.

I had some trouble uploading through FF but it seems to have worked through Safari? Can you confirm?

**Comment by luckman212** [comment]
No, I checked again just now- didn't see anything come thru on this end.

**Comment by luckman212** [comment]
I have another "file drop" set up - if you're having trouble with the transfer.sh one. Could you please try this: https://palmr.reliable.network/r/TdEqyxlDs0

**Comment by girlsperhour** [comment]
That one worked I think! I kept getting to 100% with the other one but no confirmation that it was actually done uploading.

**Comment by luckman212** [comment]
Yes! It worked. Taking a look now, thank you.

**Comment by luckman212** [comment]
@girlsperhour I notice 2 crash minidumps are referenced in the logs:

In `~/Library/Logs/DiagnosticReports`:
- `frontapp-2025-12-01-134241.ips`
- `frontapp-2025-12-01-134302.ips`

Would you be able to upload either or both of those .ips files if you can still find them?

**Comment by girlsperhour** [comment]
sent em! (all the ones I could see in that directory in fact)

**Comment by luckman212** [comment]
Great, those were helpful! Could you give [build 1.1.4](https://github.com/luckman212/frontapp/releases/tag/1.1.4) a try and let me know if it runs ok?

**Comment by girlsperhour** [comment]
Thank you for your hard work!! It's still crashing though. I'm sorry, I feel like my machine is to blame lol. :(

**Comment by luckman212** [comment]
No worries. I have some more fixes coming tomorrow, hopefully will get it sorted for you.

**Comment by luckman212** [comment]
@girlsperhour would you please give [1.1.5](https://github.com/luckman212/frontapp/releases/tag/1.1.5) a go? Hoping this one does the trick.

**Comment by girlsperhour** [comment]
No crash! It runs: `=== logging started ===`

Thank you for taking the time to sort that out! Can you explain what seemed to be the issue?

**Comment by luckman212** [comment]
That's awesome news 🎉 

Essentially it was a minor fix: I was setting the log window font to [SF Mono](https://developer.apple.com/fonts/) which, although it's installed on all systems by default, apparently isn't available for 3rd party apps to use unless manually installed from Apple's DMG.

So this new version will first try SF-Mono and fall back to a generic monospace font if it's not present.

**Comment by girlsperhour** [comment]
Crazy. And since running it I've already found Corel's CUHARM64 process to be at least one culprit of my focus-loss woes. Thank you very much for this software!!
